// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/login": {
            "post": {
                "description": "Authenticate user with nickname (creates if not exists)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create or get user by nickname",
                "parameters": [
                    {
                        "description": "Nickname",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/app.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid nickname",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/auth/logout": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Revoke authentication token",
                "produces": [
                    "application/json"
                ],
                "summary": "Logout current user",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/games/{roomId}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Retrieve current game state (personalized for player)",
                "produces": [
                    "application/json"
                ],
                "summary": "Get game state",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room ID",
                        "name": "roomId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/domain.Game"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Not a room participant",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Game not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/games/{roomId}/actions": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Player submits action: block, heal, inspect, mafia_kill, or vote",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Submit a night action or vote",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room ID",
                        "name": "roomId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Action details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/app.submitGameActionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/domain.Game"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid action",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Action not allowed for your role",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Action blocked or unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/games/{roomId}/next-phase": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Move game to next phase (resolves current phase first)",
                "produces": [
                    "application/json"
                ],
                "summary": "Advance to next game phase",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room ID",
                        "name": "roomId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/domain.Game"
                            }
                        }
                    },
                    "400": {
                        "description": "Cannot advance phase",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Only owner can advance",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/games/{roomId}/phase": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Change game phase (day/night/voting)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Set game phase manually",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room ID",
                        "name": "roomId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Phase to set",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/app.setGamePhaseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/domain.Game"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid phase",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Only owner can set phase",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/me": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Retrieve authenticated user profile",
                "produces": [
                    "application/json"
                ],
                "summary": "Get current user info",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/domain.UserSession"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/rooms": {
            "get": {
                "description": "Get all active game rooms",
                "produces": [
                    "application/json"
                ],
                "summary": "List all available rooms",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/domain.Room"
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Create a new Mafia game room",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create new game room",
                "parameters": [
                    {
                        "description": "Room details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/app.createRoomRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/domain.Room"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/rooms/{roomId}": {
            "get": {
                "description": "Retrieve specific room info",
                "produces": [
                    "application/json"
                ],
                "summary": "Get room details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room ID",
                        "name": "roomId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/domain.Room"
                            }
                        }
                    },
                    "404": {
                        "description": "Room not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/rooms/{roomId}/join": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Add current user to a room",
                "produces": [
                    "application/json"
                ],
                "summary": "Join a game room",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room ID",
                        "name": "roomId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/domain.Room"
                            }
                        }
                    },
                    "400": {
                        "description": "Cannot join room",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Room not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/rooms/{roomId}/leave": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Remove current user from a room",
                "produces": [
                    "application/json"
                ],
                "summary": "Leave a game room",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room ID",
                        "name": "roomId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Cannot leave room",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/rooms/{roomId}/start": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Begin Mafia game with current room players",
                "produces": [
                    "application/json"
                ],
                "summary": "Start a game in the room",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room ID",
                        "name": "roomId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/domain.Room"
                            }
                        }
                    },
                    "400": {
                        "description": "Cannot start game",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "app.createRoomRequest": {
            "type": "object",
            "properties": {
                "maxPlayers": {
                    "type": "integer",
                    "example": 7
                },
                "name": {
                    "type": "string",
                    "example": "Game Night"
                }
            }
        },
        "app.loginRequest": {
            "type": "object",
            "properties": {
                "nickname": {
                    "type": "string",
                    "example": "Alice"
                }
            }
        },
        "app.setGamePhaseRequest": {
            "type": "object",
            "properties": {
                "phase": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.GamePhase"
                        }
                    ],
                    "example": "day"
                }
            }
        },
        "app.submitGameActionRequest": {
            "type": "object",
            "properties": {
                "targetId": {
                    "type": "string",
                    "example": "user-123"
                },
                "type": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.GameActionType"
                        }
                    ],
                    "example": "block"
                }
            }
        },
        "domain.Game": {
            "type": "object",
            "properties": {
                "actions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.GameAction"
                    }
                },
                "activePlayerId": {
                    "type": "string"
                },
                "activePlayerNickname": {
                    "type": "string"
                },
                "activeRole": {
                    "$ref": "#/definitions/domain.GameRole"
                },
                "events": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.GameEvent"
                    }
                },
                "firstSpeakerIndex": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "phase": {
                    "$ref": "#/definitions/domain.GamePhase"
                },
                "phaseDurationSeconds": {
                    "type": "integer"
                },
                "phaseEndsAt": {
                    "type": "string"
                },
                "phaseStartedAt": {
                    "type": "string"
                },
                "players": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.GamePlayer"
                    }
                },
                "roomId": {
                    "type": "string"
                },
                "round": {
                    "type": "integer"
                },
                "speechIndex": {
                    "type": "integer"
                },
                "startedAt": {
                    "type": "string"
                },
                "step": {
                    "$ref": "#/definitions/domain.GameStep"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "domain.GameAction": {
            "type": "object",
            "properties": {
                "actorId": {
                    "type": "string"
                },
                "actorNickname": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "phase": {
                    "$ref": "#/definitions/domain.GamePhase"
                },
                "round": {
                    "type": "integer"
                },
                "targetId": {
                    "type": "string"
                },
                "targetNickname": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/domain.GameActionType"
                }
            }
        },
        "domain.GameActionType": {
            "type": "string",
            "enum": [
                "mafia_kill",
                "mistress_block",
                "inspect",
                "heal",
                "vote"
            ],
            "x-enum-varnames": [
                "GameActionMafiaKill",
                "GameActionBlock",
                "GameActionInspect",
                "GameActionHeal",
                "GameActionVote"
            ]
        },
        "domain.GameEvent": {
            "type": "object",
            "properties": {
                "actorId": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "phase": {
                    "$ref": "#/definitions/domain.GamePhase"
                },
                "round": {
                    "type": "integer"
                },
                "targetId": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "domain.GamePhase": {
            "type": "string",
            "enum": [
                "night",
                "day",
                "voting",
                "final"
            ],
            "x-enum-varnames": [
                "GamePhaseNight",
                "GamePhaseDay",
                "GamePhaseVoting",
                "GamePhaseFinal"
            ]
        },
        "domain.GamePlayer": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "isAlive": {
                    "type": "boolean"
                },
                "isOwner": {
                    "type": "boolean"
                },
                "nickname": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/domain.GameRole"
                },
                "side": {
                    "$ref": "#/definitions/domain.GameSide"
                }
            }
        },
        "domain.GameRole": {
            "type": "string",
            "enum": [
                "civilian",
                "mafia",
                "mistress",
                "commissioner",
                "doctor"
            ],
            "x-enum-varnames": [
                "GameRoleCivilian",
                "GameRoleMafia",
                "GameRoleMistress",
                "GameRoleCommissioner",
                "GameRoleDoctor"
            ]
        },
        "domain.GameSide": {
            "type": "string",
            "enum": [
                "town",
                "mafia"
            ],
            "x-enum-varnames": [
                "GameSideTown",
                "GameSideMafia"
            ]
        },
        "domain.GameStep": {
            "type": "string",
            "enum": [
                "night_mistress",
                "night_doctor",
                "night_commissioner",
                "night_mafia",
                "day_speech",
                "day_discussion",
                "voting",
                "final"
            ],
            "x-enum-varnames": [
                "GameStepNightMistress",
                "GameStepNightDoctor",
                "GameStepNightCommissioner",
                "GameStepNightMafia",
                "GameStepDaySpeech",
                "GameStepDayDiscussion",
                "GameStepVoting",
                "GameStepFinal"
            ]
        },
        "domain.Room": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "maxPlayers": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "ownerId": {
                    "type": "string"
                },
                "players": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.RoomPlayer"
                    }
                },
                "status": {
                    "$ref": "#/definitions/domain.RoomStatus"
                }
            }
        },
        "domain.RoomPlayer": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "isOwner": {
                    "type": "boolean"
                },
                "nickname": {
                    "type": "string"
                }
            }
        },
        "domain.RoomStatus": {
            "type": "string",
            "enum": [
                "waiting",
                "preparation",
                "recruiting",
                "in_progress",
                "finished"
            ],
            "x-enum-varnames": [
                "RoomStatusWaiting",
                "RoomStatusPreparing",
                "RoomStatusRecruiting",
                "RoomStatusInProgress",
                "RoomStatusFinished"
            ]
        },
        "domain.UserSession": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "description": "Type \"Bearer\" followed by a space and JWT token",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Mafia Game API",
	Description:      "Real-time Mafia game server API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
